# Generated by Django 5.2.1 on 2025-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nama_item', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('foods', 'Foods'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
