# Generated by Django 5.2.1 on 2025-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(choices=[('snack', 'Snack'), ('pastry', 'Pastry'), ('cake', 'Cake'), ('coffee', 'Coffee'), ('non_coffee', 'Non Coffee')], max_length=20),
        ),
    ]
