# Generated by Django 5.2.1 on 2025-05-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0002_alter_menu_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_pesanan', models.CharField(max_length=20, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metode_pembayaran', models.CharField(choices=[('Cash', 'Cash'), ('Debit', 'Debit'), ('Qris', 'Qris')], max_length=10)),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id_detailOrder', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_item', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainMenu.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_orders', to='mainMenu.order')),
            ],
        ),
    ]
