# Generated by Django 5.2.1 on 2025-05-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0003_order_detailorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_mode',
            field=models.CharField(choices=[('Dine-in', 'Dine-in'), ('Takeaway', 'Takeaway')], default='Dine-in', max_length=10),
        ),
    ]
