# Generated by Django 5.2.1 on 2025-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0004_order_order_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_mode',
            field=models.CharField(choices=[('Dine-in', 'Dine-in'), ('Takeaway', 'Takeaway')], max_length=10),
        ),
    ]
