# Generated by Django 5.2.1 on 2025-05-22 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0005_alter_order_order_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id_stok', models.AutoField(primary_key=True, serialize=False)),
                ('bahan_baku', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=20)),
                ('jumlah_stok', models.PositiveIntegerField()),
                ('tanggal_update', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_kadaluarsa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
