# Generated by Django 5.2.2 on 2025-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_productcategory_description_productcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
