# Generated by Django 5.2.1 on 2025-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0006_stok_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok',
            name='satuan',
            field=models.CharField(choices=[('gram', 'Gram'), ('liter', 'Liter'), ('pack', 'Pack'), ('bottle', 'Bottle')], max_length=10),
        ),
    ]
