# Generated by Django 5.2.2 on 2025-06-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
