# Generated by Django 5.2.1 on 2025-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0007_alter_stok_satuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='jenis_barang',
            field=models.CharField(choices=[('makanan', 'Bahan Baku Makanan'), ('minuman', 'Bahan Baku Minuman'), ('kemasan', 'Kemasan Pakai'), ('pendukung', 'Barang Pendukung')], default='pendukung', max_length=20),
            preserve_default=False,
        ),
    ]
